[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "-vv --maxfail=1 --disable-warnings"

[tool.ruff]
select = ["E","F","I"]
line-length = 100

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
