name: CI Observability
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  traces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests with tracing
        env:
          PYTHONPATH: .
          MOCK_AI: "true"
          OBS_BACKENDS: jsonl
          TRACE_SERVICE_NAME: pythonproject_xx
          TRACE_JSONL_PATH: trace_log.jsonl
        run: |
          python -m pytest -q --maxfail=1 --disable-warnings ^
            --cov=. --cov-report=xml:coverage.xml ^
            --junitxml=pytest-report.xml

      - name: Ensure trace file exists
        if: always()
        run: test -f trace_log.jsonl || echo '{}' > trace_log.jsonl

      - name: Upload observability artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: observability-artifacts
          path: |
            trace_log.jsonl
            coverage.xml
            pytest-report.xml
          if-no-files-found: ignore