name: CI Observability
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  traces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Run tests with tracing enabled
        env:
          PYTHONPATH: src
          MOCK_AI: "true"
          OBS_BACKENDS: jsonl
          TRACE_SERVICE_NAME: pythonproject_xx
          TRACE_JSONL_PATH: trace_log.jsonl
        run: pytest -q
      - name: Upload trace jsonl
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces-jsonl
          path: trace_log.jsonl
          if-no-files-found: ignore